execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~~~
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~3~~
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~~~3
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~-3~~
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~~~-3
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~3~~3
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~-3~~3
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~3~~-3
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~-3~~-3
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~5~~
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~~~5
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~-5~~
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~~~-5
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~5~~3
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~5~~-3
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~-5~~3
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~-5~~-3
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~3~~5
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~-3~~5
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~3~~-5
execute as @e[type=ender_dragon] at @a[r=256] run summon fec:dragon_pillar ~-3~~-5
playsound mob.enderdragon.growl @a[r=256]