scoreboard objectives remove moveCounter
scoreboard objectives remove jumpCounter
scoreboard objectives remove deathCounter
scoreboard objectives remove legendCounter
scoreboard objectives remove moveCounterDisp
scoreboard objectives remove jumpCounterDisp
scoreboard objectives remove deathCounterDisp
scoreboard objectives remove legendCounterDisp